DROP TYPE "CS669"."SEAT_ROW_LIST";
DROP TYPE "CS669"."SEAT_ROW_LIST";
DROP TABLE "CS669"."ACCESSIBLE_SEAT" cascade constraints;
DROP TABLE "CS669"."BOOKING" cascade constraints;
DROP TABLE "CS669"."BOX_SEAT" cascade constraints;
DROP TABLE "CS669"."CUSTOMER" cascade constraints;
DROP TABLE "CS669"."CUSTOMER_HISTORY" cascade constraints;
DROP TABLE "CS669"."MOVIE" cascade constraints;
DROP TABLE "CS669"."NORMAL_SEAT" cascade constraints;
DROP TABLE "CS669"."RECLINING_SEAT" cascade constraints;
DROP TABLE "CS669"."SEAT" cascade constraints;
DROP TABLE "CS669"."SEAT_RESERVATION" cascade constraints;
DROP TABLE "CS669"."SHIPPING_OFFERING" cascade constraints;
DROP TABLE "CS669"."SHOWTIME" cascade constraints;
DROP TABLE "CS669"."TAX_RATES" cascade constraints;
DROP TABLE "CS669"."THEATER" cascade constraints;
DROP TABLE "CS669"."SEAT" cascade constraints;
DROP TABLE "CS669"."CUSTOMER" cascade constraints;
DROP TABLE "CS669"."SHOWTIME" cascade constraints;
DROP TABLE "CS669"."THEATER" cascade constraints;
DROP TABLE "CS669"."BOOKING" cascade constraints;
DROP TABLE "CS669"."MOVIE" cascade constraints;
DROP TABLE "CS669"."TAX_RATES" cascade constraints;
DROP TABLE "CS669"."ACCESSIBLE_SEAT" cascade constraints;
DROP TABLE "CS669"."BOX_SEAT" cascade constraints;
DROP TABLE "CS669"."NORMAL_SEAT" cascade constraints;
DROP TABLE "CS669"."RECLINING_SEAT" cascade constraints;
DROP TABLE "CS669"."SEAT_RESERVATION" cascade constraints;
DROP TABLE "CS669"."SHIPPING_OFFERING" cascade constraints;
DROP TABLE "CS669"."CUSTOMER_HISTORY" cascade constraints;
DROP PROCEDURE "CS669"."ADD_CUSTOMER";
DROP PROCEDURE "CS669"."ADD_SHOWTIME";
DROP PROCEDURE "CS669"."ADD_THEATER";
DROP PROCEDURE "CS669"."MAKE_BOOKING";
