REM INSERTING into CS669.SHIPPING_OFFERING
SET DEFINE OFF;
Insert into CS669.SHIPPING_OFFERING (SHIPPING_OFFERING_ID,OFFERING) values (50,'SAME DAY');
Insert into CS669.SHIPPING_OFFERING (SHIPPING_OFFERING_ID,OFFERING) values (51,'OVERNIGHT');
Insert into CS669.SHIPPING_OFFERING (SHIPPING_OFFERING_ID,OFFERING) values (52,'TWO DAY');
