REM INSERTING into CS669.THEATER
SET DEFINE OFF;
Insert into CS669.THEATER (THEATER_ID,THEATER_NAME,THTR_STREET,THTR_CITY,THTR_STATE,THTR_ZIPCODE,TAX_RATE_ID) values ('3','REGAL CONCORD 67','Main St','Concord','NH',1267,'30');
Insert into CS669.THEATER (THEATER_ID,THEATER_NAME,THTR_STREET,THTR_CITY,THTR_STATE,THTR_ZIPCODE,TAX_RATE_ID) values ('4','CLASSIC TALKIES London 21','Baker St','London','NY',1137,'33');
Insert into CS669.THEATER (THEATER_ID,THEATER_NAME,THTR_STREET,THTR_CITY,THTR_STATE,THTR_ZIPCODE,TAX_RATE_ID) values ('1','ANC BOSTON 1989','Boston Common St','Boston','MA',2130,'22');
Insert into CS669.THEATER (THEATER_ID,THEATER_NAME,THTR_STREET,THTR_CITY,THTR_STATE,THTR_ZIPCODE,TAX_RATE_ID) values ('2','ANC BURLINGTON 2018','Buffalo St','Burlington','VT',1802,'46');
